import { expect, test } from '@playwright/test'
import { churchId, expectNoSeriousAccessibilityIssues, json, mockCsrf } from './support'

test.use({serviceWorkers:'block'})
const session={id:11,email_verified:true,mfa_confirmed:true,workspaces:[{church_id:churchId,name:'Synthetic church',role:'owner'}]}

test('a verified applicant without membership deliberately continues to the allowlisted application destination',async({page,context})=>{
 await context.route('**/auth/session',route=>json(route,{...session,workspaces:[]}))
 await page.goto('/account?returnTo=%2Faccount%2Fapplication')
 await expect(page.getByRole('link',{name:'Continue to requested destination'})).toHaveAttribute('href','/account/application')
 await expect(page).toHaveURL(/\/account\?returnTo=/)
 await expectNoSeriousAccessibilityIssues(page)
})

test('invitation mismatch preserves non-secret inputs and an uncertain redemption prevents repeat mutation',async({page,context})=>{
 await mockCsrf(context)
 const proof={church_id:churchId,invitation_id:'00000000-0000-4000-8000-000000000070',token:'a'.repeat(64),signature:'b'.repeat(64),expires:2000000000}
 let posts=0
 await context.route('**/api/teacher-invitations/accept',route=>{posts++;return posts===1?json(route,{message:'untrusted response text'},403):route.abort('failed')})
 await page.goto('/account/teacher-invitation#'+encodeURIComponent(JSON.stringify(proof)))
 await page.getByLabel('Invited email').fill('invited@example.test')
 await page.getByRole('checkbox',{name:'Create my invited account'}).check()
 await page.getByLabel('Display name').fill('Synthetic invited teacher')
 await page.getByLabel('New password').fill('Synthetic-password1!')
 await page.getByRole('button',{name:'Accept invitation'}).click()
 await expect(page.getByRole('alert')).toContainText('Use the invited account')
 await expect(page.getByRole('alert')).not.toContainText('untrusted response text')
 await expect(page.getByLabel('Invited email')).toHaveValue('invited@example.test')
 await expect(page.getByLabel('Display name')).toHaveValue('Synthetic invited teacher')
 await expect(page.getByLabel('New password')).toHaveValue('')
 await page.getByLabel('New password').fill('Synthetic-password1!')
 await page.getByRole('button',{name:'Accept invitation'}).click()
 await expect(page.getByText(/Check Account and ask your church Owner/)).toBeVisible()
 await expect(page.getByRole('button',{name:'Accept invitation'})).toBeDisabled()
 expect(posts).toBe(2)
 expect(new URL(page.url()).hash).toBe('')
 await expectNoSeriousAccessibilityIssues(page)
})

test('Account reload and deliberate assurance continuation never treat enrollment as current-session MFA',async({page,context})=>{
 await mockCsrf(context)
 await context.route('**/auth/session',route=>json(route,session))
 await context.route('**/api/me',route=>json(route,{id:11,memberships:[{church_id:churchId,status:'active',role:'owner'}],active_session:{mfa_confirmed:false},assignments:{ministry_ids:[]}}))
 const returnTo=encodeURIComponent(`/account/home?church=${churchId}`)
 await page.goto(`/account?returnTo=${returnTo}`)
 await expect(page.getByText('Email: Verified')).toBeVisible()
 await expect(page.getByRole('button',{name:'Sign in',exact:true})).toHaveCount(0)
 await expect(page).toHaveURL(/\/account\?returnTo=/)
 await expectNoSeriousAccessibilityIssues(page)
 await page.getByRole('link',{name:'Continue to church Home',exact:true}).click()
 await expect(page.getByText(/Check your membership and current-session MFA/)).toBeVisible()
 await page.getByRole('link',{name:'Check MFA'}).click()
 await expect(page.getByText(/Your authenticator is already confirmed/)).toBeVisible()
 await expect(page.getByRole('button',{name:'Set up authenticator'})).toHaveCount(0)
})

test('sign-in, challenge and verification remain separate and require deliberate return after authentication',async({page,context})=>{
 await mockCsrf(context)
 await context.route('**/login',route=>route.request().isNavigationRequest()?route.fallback():json(route,{two_factor:true}))
 await context.route('**/two-factor-challenge',route=>json(route,{}))
 await context.route('**/auth/session',route=>json(route,session))
 const returnTo=encodeURIComponent(`/account/home?church=${churchId}`)
 await page.goto(`/account/login?returnTo=${returnTo}`)
 await page.getByLabel('Email',{exact:true}).fill('synthetic@example.test')
 await page.getByLabel('Password',{exact:true}).fill('Synthetic-password1!')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByLabel('Authenticator code').fill('123456')
 await page.getByRole('button',{name:'Verify sign-in'}).click()
 await expect(page.getByRole('heading',{name:'Your account',exact:true})).toBeVisible()
 await expect(page).toHaveURL(/\/account\/login\?returnTo=/)
 await expect(page.getByRole('link',{name:'Continue to church Home'})).toHaveAttribute('href',`/account/home?church=${churchId}`)
 await expectNoSeriousAccessibilityIssues(page)
 await page.goto('/account?returnTo=https%3A%2F%2Foutside.example%2F')
 await expect(page.getByRole('link',{name:'Continue to church Home'})).toHaveAttribute('href','/account/home')
 let challenges=0
 await context.route('**/two-factor-challenge',route=>{challenges++;return route.abort('failed')})
 await page.goto(`/account/login?returnTo=${returnTo}`)
 await page.getByLabel('Email',{exact:true}).fill('synthetic@example.test')
 await page.getByLabel('Password',{exact:true}).fill('Synthetic-password1!')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByLabel('Authenticator code').fill('123456')
 await page.getByRole('button',{name:'Verify sign-in'}).click()
 await expect(page.getByRole('button',{name:'Verify sign-in'})).toBeDisabled()
 await context.route('**/auth/session',route=>json(route,{},401))
 await page.getByRole('button',{name:'Continue signed-in session'}).click()
 await expect(page.getByRole('button',{name:'Verify sign-in'})).toBeEnabled()
 await context.route('**/auth/session',route=>json(route,session))
 await page.getByLabel('Authenticator code').fill('123456')
 await page.getByRole('button',{name:'Verify sign-in'}).click()
 await expect(page.getByRole('button',{name:'Verify sign-in'})).toBeDisabled()
 await page.getByRole('button',{name:'Continue signed-in session'}).click()
 await expect(page.getByRole('heading',{name:'Your account',exact:true})).toBeVisible()
 expect(challenges).toBe(2)
 await expectNoSeriousAccessibilityIssues(page)
})

test('application keeps field errors and non-secret values while requiring fresh verification',async({page,context})=>{
 await mockCsrf(context)
 await page.addInitScript(()=>{window.turnstile={render:(_,options)=>{options.callback('synthetic-proof');return 'synthetic-widget'},remove:()=>undefined}})
 await context.route('**/auth/session',route=>json(route,session))
 await context.route('**/api/church-applications/current',route=>json(route,{application:null}))
 await context.route('**/api/church-applications',route=>json(route,{field_errors:{city:['untrusted response text']}},422))
 await page.goto('/account/application')
 await page.getByLabel('Church name').fill('Synthetic church')
 await page.getByLabel('City',{exact:true}).fill('Synthetic city')
 await page.getByRole('button',{name:'Submit application'}).click()
 await expect(page.getByRole('alert')).toBeFocused()
 await expect(page.getByRole('alert')).not.toContainText('untrusted response text')
 await expect(page.getByLabel('City',{exact:true})).toHaveAttribute('aria-invalid','true')
 await page.getByRole('button',{name:'Refresh status'}).click()
 await expect(page.getByLabel('Church name')).toHaveValue('Synthetic church')
 await expect(page.getByLabel('City',{exact:true})).toHaveValue('Synthetic city')
 await expectNoSeriousAccessibilityIssues(page)
})

test('uncertain application outcome blocks repeat mutation and reconciles the accepted result',async({page,context})=>{
 await mockCsrf(context)
 await page.addInitScript(()=>{window.turnstile={render:(_,options)=>{options.callback('synthetic-proof');return 'synthetic-widget'},remove:()=>undefined}})
 await context.route('**/auth/session',route=>json(route,session))
 let accepted=false,posts=0
 await context.route('**/api/church-applications/current',route=>json(route,{application:accepted?{id:'00000000-0000-4000-8000-000000000060',status:'pending',church_name:'Synthetic church'}:null}))
 await context.route('**/api/church-applications',async route=>{posts++;accepted=true;await route.abort('failed')})
 await page.goto('/account/application');await page.getByLabel('Church name').fill('Synthetic church');await page.getByLabel('City',{exact:true}).fill('Synthetic city')
 await page.getByRole('button',{name:'Submit application'}).click()
 await expect(page.getByRole('button',{name:'Submit application'})).toBeDisabled()
 await page.getByRole('button',{name:'Check submission outcome'}).click()
 await expect(page.getByRole('heading',{name:'Pending review'})).toBeVisible()
 expect(posts).toBe(1)
 await expect(page.getByLabel('Church name')).toHaveCount(0)
})

test('application approval continues through MFA and verified Home rather than a business operation',async({page,context})=>{
 await context.route('**/auth/session',route=>json(route,session))
 await context.route('**/api/church-applications/current',route=>json(route,{application:{id:'00000000-0000-4000-8000-000000000060',status:'approved',church_name:'Synthetic church',church_id:churchId}}))
 await context.route('**/api/me',route=>json(route,{id:11,memberships:[{church_id:churchId,status:'active',role:'owner'}],active_session:{mfa_confirmed:true},assignments:{ministry_ids:[]}}))
 await page.goto('/account/application')
 await expect(page.getByRole('link',{name:'Continue to church Home'})).toHaveAttribute('href',`/account/home?church=${churchId}`)
 await page.getByRole('link',{name:'Continue to church Home'}).click()
 await expect(page.getByRole('heading',{name:'Home',exact:true})).toBeVisible()
 await expectNoSeriousAccessibilityIssues(page)
})

test('application states reflow with keyboard errors, enlarged text and generic offline presentation',async({page,context})=>{
 await context.route('**/auth/session',route=>json(route,session))
 await context.route('**/api/church-applications/current',route=>json(route,{application:{id:'00000000-0000-4000-8000-000000000060',status:'rejected',church_name:'Synthetic church',reason:'Synthetic explanation'}}))
 for(const width of [320,390,768,1024,1440]){
  await page.setViewportSize({width,height:1000});await page.goto('/account/application')
  await expect(page.getByRole('heading',{name:'Rejected',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await expectNoSeriousAccessibilityIssues(page)
 }
 await page.setViewportSize({width:320,height:1000});await page.addStyleTag({content:':root { font-size: 200%; }'})
 await page.emulateMedia({reducedMotion:'reduce',forcedColors:'active'})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:test.info().outputPath('application-enlarged.png'),fullPage:true})
 await context.setOffline(true);await page.evaluate(()=>dispatchEvent(new Event('offline')))
 await expect(page.getByText('Synthetic church',{exact:true})).toHaveCount(0)
 expect(await page.locator('main').ariaSnapshot()).not.toMatch(/Synthetic explanation|Rejected/)
})
