/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            /** Format: uuid */
            correlation_id: string;
            field_errors?: {
                [key: string]: string[];
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        PageMeta: {
            next_cursor: string | null;
            has_more: boolean;
        };
        SyncPushRequest: {
            /** Format: uuid */
            device_id: string;
            /** Format: uuid */
            batch_id: string;
            events: {
                [key: string]: unknown;
            }[];
        };
        SyncPushResponse: {
            results: {
                [key: string]: unknown;
            }[];
        };
        SyncPullResponse: {
            changes: {
                [key: string]: unknown;
            }[];
            page: components["schemas"]["PageMeta"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Safe API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
